<a href="https://colab.research.google.com/github/bionca22/exercicio_de_base_numpy/blob/main/Desafio_Python_Pandas.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Desafio 1 - Importando dataset pelo pydataset
dupla: Ana e Gislaine

In [ ]:
!pip install pydataset

Collecting pydataset
  Downloading pydataset-0.2.0.tar.gz (15.9 MB)
     ━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━━ 15.9/15.9 MB 50.6 MB/s eta 0:00:00
  Preparing metadata (setup.py) ... done
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from pydataset) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pydataset) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pydataset) (2023.4)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas->pydataset) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->pydataset) (1.16.0)
Building wheels for collected packages: pydataset
  Building wheel for pydataset (setup.py) ... done
  Created wheel for pydataset: filename=pydataset-0.2.0-py3-none-any.whl size=15939416 sha256=92e4bac27a45b0cb2c534c3c38f90631578703f212b0d79f8bcbfecc5f09f5db
  Stored in directory: /root/.cache/pip/wheels/2b/83/5c/073c3755e8b7704e4677557b2055e61026c1a2342149214c13
Successfully built pydataset
Installing collected packages: pydataset
Successfully installed pydataset-0.2.0

In [ ]:
from pydataset import data

initiated datasets repo at: /root/.pydataset/

In [ ]:
database=data("plantTraits")

In [ ]:
database.head()

,pdias,longindex,durflow,height,begflow,mycor,vegaer,vegsout,autopoll,insects,...,seashiv,seasver,everalw,everparti,elaio,endozoo,epizoo,aquat,windgl,unsp
Aceca,96.84,0.000000,2,7,5,2.0,0.0,0.0,0,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
Aceps,110.72,0.000000,3,8,4,2.0,0.0,0.0,0,4,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0
Agrca,0.06,0.666667,3,2,6,2.0,0.0,1.0,0,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Agrst,0.08,0.488889,2,2,7,1.0,2.0,0.0,0,0,...,0.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0
Ajure,1.48,0.476190,3,2,5,2.0,2.0,0.0,1,3,...,0.0,0.0,1.0,0.0,1.0,0.0,0.0,0.0,0.0,0.0

In [ ]:
type(database)

pandas.core.frame.DataFrame

In [ ]:
Num_linhas=database.shape[0]
Num_colunas = database.shape[1]

print("o dataframe possui",Num_linhas,"linhas")
print("o dataframe possui",Num_colunas,"linhas")

o dataframe possui 136 linhas
o dataframe possui 31 linhas

# Desafio 2: Conversão

dupla:

Dicas:
- 1 polegada = 2,54 centímetros
- 1 libra = 0,45 quilos
- use o método .plot.scatter()

In [ ]:
import pandas as pd

In [ ]:
d2women=data("women")

In [ ]:
d2women.head()

### 1. Construa uma nova representação onde os nomes das colunas estão em português, e os valores de altura são convertidos para centímetros e os valores de peso convertidos para quilograma.

### 2. Plote o scatterplot de altura x peso da nova representação.

#Desafio 3: Titanic
dupla: Lais e Débora

In [ ]:
import pandas as pd

In [ ]:
from pydataset import data

In [ ]:
d3titanic = data("titanic")

In [ ]:
d3titanic.head()

       class     age  sex survived
1  1st class  adults  man      yes
2  1st class  adults  man      yes
3  1st class  adults  man      yes
4  1st class  adults  man      yes
5  1st class  adults  man      yes

### 1. Quantas pessoas sobreviveram e quantas morreram?

In [ ]:
d3titanic['survived'].value_counts()

no     817
yes    499
Name: survived, dtype: int64

### 2. Quantas pessoas eram da primeira, segunda e terceira classe?

In [ ]:
d3titanic['class'].value_counts()

3rd class    706
1st class    325
2nd class    285
Name: class, dtype: int64

### 3. Qual a porcentagem de sobreviventes na primeira classe?

In [ ]:
sobreviventes = d3titanic[['class', 'survived']].groupby(['class']).value_counts(normalize = True *100)

In [ ]:
sobreviventes[0:2]

class      survived
1st class  yes         0.624615
           no          0.375385
dtype: float64

### 4. Qual a porcentagem de mortos da terceira classe?

In [ ]:
sobreviventes[-2:]

class      survived
3rd class  no          0.747875
           yes         0.252125
dtype: float64

#Desafio 4: Futebol

#Desafio 5: Desafio 5: Forbes - Gravar Vídeo

dupla: Todo Squad <3

In [ ]:
!pip install pydataset

Requirement already satisfied: pydataset in /usr/local/lib/python3.10/dist-packages (0.2.0)
Requirement already satisfied: pandas in /usr/local/lib/python3.10/dist-packages (from pydataset) (1.5.3)
Requirement already satisfied: python-dateutil>=2.8.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pydataset) (2.8.2)
Requirement already satisfied: pytz>=2020.1 in /usr/local/lib/python3.10/dist-packages (from pandas->pydataset) (2023.4)
Requirement already satisfied: numpy>=1.21.0 in /usr/local/lib/python3.10/dist-packages (from pandas->pydataset) (1.23.5)
Requirement already satisfied: six>=1.5 in /usr/local/lib/python3.10/dist-packages (from python-dateutil>=2.8.1->pandas->pydataset) (1.16.0)

In [ ]:
from pydataset import data

In [ ]:
df_forbes=data("Forbes2000")
df_forbes

,rank,name,country,category,sales,profits,assets,marketvalue
1,1,Citigroup,United States,Banking,94.71,17.85,1264.03,255.30
2,2,General Electric,United States,Conglomerates,134.19,15.59,626.93,328.54
3,3,American Intl Group,United States,Insurance,76.66,6.46,647.66,194.87
4,4,ExxonMobil,United States,Oil & gas operations,222.88,20.96,166.99,277.02
5,5,BP,United Kingdom,Oil & gas operations,232.57,10.27,177.57,173.54
...,...,...,...,...,...,...,...,...
1996,1996,Siam City Bank,Thailand,Banking,0.48,0.02,11.27,1.47
1997,1997,Yokogawa Electric,Japan,Business services & supplies,2.78,-0.22,2.96,3.29
1998,1998,Hindalco Industries,India,Materials,1.35,0.14,2.47,2.76
1999,1999,Nexans,France,Capital goods,5.09,0.00,2.71,0.88
2000,2000,Oriental Bank of Commerce,India,Banking,0.81,0.10,7.16,1.17

## 1. Qual a empresa mais valiosa da lista da Forbes 2000?

In [ ]:
mais_valioso = df_forbes.sort_values('marketvalue', ascending = False).head(1)
mais_valioso

   rank              name        country       category   sales  profits  assets  marketvalue
2     2  General Electric  United States  Conglomerates  134.19    15.59  626.93       328.54

## 2. Construa uma tabela com as TOP 10 empresas mais lucrativas da lista.

In [ ]:
top_10_empresas_lucrativas = df_forbes.nlargest(10, 'profits')
tabela_nome_lucro = top_10_empresas_lucrativas[['name', 'profits']]
print(tabela_nome_lucro)

                name  profits
4         ExxonMobil    20.96
1          Citigroup    17.85
2   General Electric    15.59
6    Bank of America    10.81
5                 BP    10.27
20       Freddie Mac    10.09
22      Altria Group     9.20
10   Wal-Mart Stores     9.05
31         Microsoft     8.88
17             Total     8.84

## 3. Qual a média de valores de empresa das cinco categorias mais valiosas?

In [ ]:
top_5_empresas_mais_valiosas = df_forbes.groupby("category")['marketvalue'].mean().head()
top_5_empresas_mais_valiosas

category
Aerospace & defense             12.059474
Banking                         10.353067
Business services & supplies     7.166000
Capital goods                    6.276981
Chemicals                        8.001200
Name: marketvalue, dtype: float64